#!/bin/sh

#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --auto
#xrandr --dpi 96

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# if [ -x $HOME/.config/bspwm/scripts/own_script_bspwm_laptop_dual_monitor ];then
#     $HOME/.config/bspwm/scripts/own_script_bspwm_laptop_dual_monitor
# fi

bspc config border_width             1
bspc config window_gap               0
bspc config automatic_scheme         longest_side

bspc config split_ratio              0.52
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config single_monocle           true
bspc config focus_follows_pointer    true
bspc config pointer_motion_interval  5

bspc config normal_border_color      "#25282B"
bspc config focused_border_color     "#F0C674"

INTERNAL_MONITOR="eDP-1-1"
EXTERNAL_MONITOR="HDMI-1-1"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  bspc desktop Desktop --remove
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d VI VII VIII IX X
    bspc monitor "$INTERNAL_MONITOR" -d I II III IV V
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d I II III IV V VI VII VIII IX X
  fi
fi

$HOME/.config/polybar/launch.sh &

# bspc monitor eDP-1-1 -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-1-1 -d 6 7 8 9 0

feh --bg-fill -N $HOME/.config/wallpaper/bg.png &

dunst --config $HOME/.config/dunst/dunstrc &

piactl connect &

megasync &

bspc rule -a Chromium desktop=^2
bspc rule -a firefox desktop=^2
bspc rule -a telegram desktop=^4
bspc rule -a Gimp desktop=^8 state=floating
bspc rule -a mattermost desktop=^0
bspc rule -a keepassxc desktop=^9
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  # set xrandr rules for docked setup
  xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --primary --mode 1920x1080 --pos 1920x0 --rotate normal
  if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 5 ]]; then
    monitor_add
  fi
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
  # set xrandr rules for mobile setup
  xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --off
  if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
    monitor_remove
  fi
fi
