theme = "onedark"

[editor]
auto-pairs = false
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 50
line-number = "relative"
mouse = false
scroll-lines = 1
shell = ["zsh", "-c"]

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "position-percentage", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [editor.whitespace]
# render = "all"

[keys.normal.b]
c = ":buffer-close"
n = ":new"
